nome = input('Ola usuario qual e o seu nome?')
idade = input('ok, qual sua idade?')
print('cadastro concluido.',nome,idade,'anos')
print('tbm temos sistemas de codificação de data de nascimento, olhe a seguir.')
dia = input('Que dia vc nasceu?')
mes = input('Que mes vc nasceu?')
ano = input('Que ano vc nasceu?')
print('pelos meus calculos, vc nasceu dia',dia,'de',mes,'de',ano)
print('ou seja, vc tem',idade,'anos')
print('script feito por Ryankkkkkkk.')
